BLOCK_FIELDS_TO_EXPORT = [
    "number",
    "hash",
    "parent_hash",
    "nonce",
    "sha3_uncles",
    "logs_bloom",
    "transactions_root",
    "state_root",
    "receipts_root",
    "miner",
    "difficulty",
    "total_difficulty",
    "size",
    "extra_data",
    "gas_limit",
    "gas_used",
    "timestamp",
    "transaction_count",
    "base_fee_per_gas",
    "withdrawals_root",
    "withdrawals",
    "blob_gas_used",
    "excess_blob_gas",
]

TRANSACTION_FIELDS_TO_EXPORT = [
    "hash",
    "nonce",
    "block_hash",
    "block_number",
    "transaction_index",
    "from_address",
    "to_address",
    "value",
    "gas",
    "gas_price",
    "input",
    "block_timestamp",
    "max_fee_per_gas",
    "max_priority_fee_per_gas",
    "transaction_type",
    "max_fee_per_blob_gas",
    "blob_versioned_hashes",
    "access_list",
]


CONTRACT_FIELDS = [
    "address",
    "bytecode",
    "function_sighashes",
    "is_erc20",
    "is_erc721",
    "block_number",
]
